name: aa-geneformer-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.20
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.12.0
  - scikit-learn>=1.5,<2
  - pytorch=2.4.1
  - pytorch-cuda=11.8
  - pip
  - pip:
      - transformers==4.46.0
